name: main workflow

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Fetch project files
              uses: actions/checkout@v3
            - name: 'Create env file'
              run: |
                  touch .env
                  echo "PORT=300052\nAPI_PREFIX=/api/v1\nNODE_ENV=development\nRATE_LIMIT_MAX=100\nRATE_LIMIT_WINDOW=60000" >> .env
            - name: Build Docker image
              uses: wshihadeh/docker-deployment-action@v2
              with:
                  remote_docker_host: ${{ secrets.DOCKER_HOST_DEV }}
                  remote_docker_port: 2222
                  ssh_private_key: ${{ secrets.DOCKER_SSH_PRIV_KEY_DEV }}
                  ssh_public_key: ${{ secrets.DOCKER_SSH_PUB_KEY_DEV }}
                  deployment_mode: docker-compose
                  stack_file_name: docker-compose.yaml
                  args: build
                  docker_prune: 'false'
                  pull_images_first: 'false'
    test:
        needs: build
        runs-on: self-hosted
        steps:
            - name: checkout repo
              uses: actions/checkout@v3
            - name: use node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
            - run: npm install
            - run: npm test
    deploy:
        needs: test
        runs-on: self-hosted
        steps:
            - name: Fetch project files
              uses: actions/checkout@v3
            - name: Deploy to Docker Host
              uses: wshihadeh/docker-deployment-action@v2
              with:
                  remote_docker_host: ${{ secrets.DOCKER_HOST_DEV }}
                  remote_docker_port: 2222
                  ssh_private_key: ${{ secrets.DOCKER_SSH_PRIV_KEY_DEV }}
                  ssh_public_key: ${{ secrets.DOCKER_SSH_PUB_KEY_DEV }}
                  deployment_mode: docker-compose
                  stack_file_name: docker-compose.yaml
                  args: up -d
                  docker_prune: 'false'
                  pull_images_first: 'false'
